# Generated by Django 3.2.6 on 2021-09-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210925_0618'),
        ('accounts', '0019_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Comic',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
